import "./globals.css";
import Navbar from "./Navbar";
import Head from "next/head";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <title>Aaqib Shaheer | QA Engineer</title>
        <link rel="icon" href="/myFavicon.png" type="image/png" />
      </Head>
      <body className="site-bg">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
